### ISSUE TITLE
[Feature] Localization of any number of tags at high frequency

### ISSUE THREAD

**Issue by AlexisTM** [wallarelvo/decawave_localization#1]
Did you consider implementing a GPS like protocol for the DWM1000?

This requires:
* Synchronizing the timestamps of all devices;
* Each anchor send its position and current timestamp;
* From the positions and timestamps received, the devices compute their position.

Pros:
* Works with any number of tags are they are in "listening only" mode;
* Adding an anchor do not require to change the configuration of each tag;
* The tags are "stupid" and thus do not need more configuration than the band, power, ... and can join any network seamlessly.

Cons: 
* The timestamp synchronization must be precise;
* The anchors must send their messages in a synchronous way.

**Comment by AdnWa** [comment]
For this, we need forward TDoA ?

**Comment by a20r** [comment]
Wow, sorry guys. Totally forgot about this issue. I would prefer not to require synchronization between any of the nodes. This just makes it easier to use out of the box. What do you guys think?

**Comment by AlexisTM** [comment]
@AdnWa Forward TDOA is the opposite: The anchors only receive data and the tags are sending messages at random time.

The anchor data is processed onto a central server and knows the position of each tag. Badly; the tag (aka robot) has no idea where he is.  (asset management) This can go at a pretty high frequency (can be different for each tag) because there is only one message from the tag to be sent.

On the Reverse TDOA; The tags only know their position at high frequency. 
Bitcraze is implementing it: https://www.bitcraze.io/loco-pos-system/ This is also open-source.

**Comment by AlexisTM** [comment]
Outdated.
